import type { AgendaBlock, AgendaTrack, AgendaTrackId, ScheduleTrackId } from "./types";

const local = (es: string, en = es) => ({ es, en });

/** Rooms and the independent stream in the published programme. */
export const agendaTracks = [
  {
    id: "bisa",
    kind: "room",
    name: local("Auditorio BISA", "BISA Auditorium"),
    shortName: local("BISA"),
    code: "01",
    accent: "orange",
    room: "Main Stage",
    description: local("Escenario principal", "Main stage"),
    topics: { es: [], en: [] },
    icon: "rocket",
  },
  {
    id: "gessell",
    kind: "room",
    name: local("Salón Gessell", "Gessell Hall"),
    shortName: local("Gessell"),
    code: "02",
    accent: "sky",
    room: "Secondary Stage",
    description: local("Escenario secundario", "Secondary stage"),
    topics: { es: [], en: [] },
    icon: "ai",
  },
  {
    id: "a1",
    kind: "room",
    name: local("Arquitectura 1", "Architecture 1"),
    shortName: local("A1"),
    code: "03",
    accent: "purple",
    room: "Specialized talks",
    description: local("Charlas especializadas", "Specialized talks"),
    topics: { es: [], en: [] },
    icon: "key",
  },
  {
    id: "d1",
    kind: "room",
    name: local("Diseño 1", "Design 1"),
    shortName: local("D1"),
    code: "04",
    accent: "green",
    room: "Specialized talks",
    description: local("Charlas especializadas", "Specialized talks"),
    topics: { es: [], en: [] },
    icon: "bolt",
  },
  {
    id: "l29",
    kind: "room",
    name: local("Laboratorio 29", "Lab 29"),
    shortName: local("L29"),
    code: "05",
    accent: "sky",
    room: "BYOD",
    description: local("Laboratorio BYOD", "BYOD lab"),
    topics: { es: [], en: [] },
    icon: "dumbbell",
  },
  {
    id: "l22",
    kind: "room",
    name: local("Laboratorio 22", "Lab 22"),
    shortName: local("L22"),
    code: "06",
    accent: "green",
    room: "PC lab",
    description: local("Laboratorio con PCs", "Computer lab"),
    topics: { es: [], en: [] },
    icon: "dumbbell",
  },
  {
    id: "virtual-es",
    kind: "virtual",
    name: local("Virtual · Español", "Virtual · Spanish"),
    shortName: local("Virtual ES"),
    code: "07",
    accent: "purple",
    room: "Online",
    description: local("Stream virtual en español", "Virtual stream in Spanish"),
    topics: { es: [], en: [] },
    icon: "ai",
  },
  {
    id: "virtual-en",
    kind: "virtual",
    name: local("Virtual · Inglés", "Virtual · English"),
    shortName: local("Virtual EN"),
    code: "08",
    accent: "sky",
    room: "Online",
    description: local("Stream virtual en inglés", "Virtual stream in English"),
    topics: { es: [], en: [] },
    icon: "ai",
  },
] as const satisfies readonly AgendaTrack[];

export function getAgendaTrack(id: ScheduleTrackId): AgendaTrack {
  const track = agendaTracks.find((item) => item.id === id);
  if (!track) throw new Error(`Sala desconocida: ${id}`);
  return track;
}

const session = (
  id: string,
  trackId: AgendaTrackId,
  title: string,
  speakers: readonly string[],
  format: "charla" | "taller" | "demo" | "panel" | "caso" = "charla",
  level?: "intro" | "intermedio" | "avanzado",
  time?: {
    start: `${number}${number}:${number}${number}`;
    end: `${number}${number}:${number}${number}`;
  },
) => ({
  kind: "session" as const,
  id,
  trackId,
  status: "confirmed" as const,
  title,
  speakers,
  format,
  level,
  time,
});

/** Published programme, including the Spanish and English virtual streams. */
export const agenda = [
  {
    kind: "plenary",
    id: "registro",
    time: { start: "08:00", end: "09:00" },
    subtype: "registration",
    title: local("Registro + Community Expo", "Registration + Community Expo"),
    summary: local(
      "Acreditación, stands, networking inicial y visuales del evento.",
      "Check-in, booths, early networking and event visuals.",
    ),
  },
  {
    kind: "plenary",
    id: "opening",
    time: { start: "09:00", end: "09:20" },
    subtype: "opening",
    title: local("Opening — AWS Student Community Day Cochabamba 2026"),
    summary: local(
      "Bienvenida, comunidades, sponsors, tracks y espacios.",
      "Welcome, communities, sponsors, tracks and spaces.",
    ),
  },
  {
    kind: "parallel",
    id: "bloque-1",
    time: { start: "09:20", end: "10:00" },
    label: local("Bloque 1", "Block 1"),
    sessions: [
      session(
        "b1-carlos",
        "gessell",
        "Building Autonomous AI on AWS: From Bedrock to Real-World Agent Systems",
        ["Carlos Olivera"],
        "charla",
        "intermedio",
      ),
      session(
        "b1-victor",
        "bisa",
        "Monitorea como un Pro: CloudWatch + APIs .NET en tiempo real",
        ["Victor Altamirano"],
        "charla",
        "intermedio",
      ),
      session(
        "b1-marlene",
        "l22",
        "Construye tu primera app de IA con AWS + PartyRock",
        ["Marlene Choque Perez", "Araceli Ivana Challapa Montaño"],
        "taller",
        "intro",
      ),
    ],
  },
  {
    kind: "parallel",
    id: "bloque-2",
    time: { start: "10:05", end: "10:45" },
    label: local("Bloque 2", "Block 2"),
    sessions: [
      session(
        "b2-rodrigo",
        "l22",
        "De programar con IA a construir con agentes",
        ["Rodrigo Torrico"],
        "charla",
        "intermedio",
      ),
      session(
        "b2-silvana",
        "bisa",
        "Sin datos no hay IA: construyendo un pipeline ETL serverless en AWS",
        ["Silvana Gutierrez", "Micaela Belen Challapa Montaño"],
        "charla",
        "intermedio",
      ),
      session(
        "b2-juan",
        "a1",
        "El mindset DevOps que nadie te enseña en la universidad",
        ["Juan Rodrigo Villarroel Calderon"],
        "charla",
        "intro",
      ),
      session(
        "b2-freddy",
        "gessell",
        "De la idea al código: construyamos una aplicación con AI-DLC",
        ["Freddy Aguilar Rojas", "Natalia Alfaro"],
        "taller",
        "intro",
      ),
      session(
        "v3",
        "virtual-es",
        "Construye tu Primer MCP Server de Seguridad en AWS",
        ["Jorge Barreto"],
        "charla",
        "intermedio",
      ),
      session(
        "v1",
        "virtual-en",
        "From Complex Orchestration to Declarative Data Pipelines with AWS Glue",
        ["Vikneshwara R B"],
        "charla",
        "intermedio",
      ),
    ],
  },
  {
    kind: "plenary",
    id: "break-1",
    time: { start: "10:45", end: "11:00" },
    subtype: "break",
    title: local("Community Break"),
    summary: local(
      "Coffee, expo, sponsors, comunidades y desplazamiento. Los streams virtuales también entran en pausa.",
      "Coffee, expo, sponsors, communities and room changes. The virtual streams also pause.",
    ),
  },
  {
    kind: "parallel",
    id: "bloque-3",
    time: { start: "11:00", end: "11:40" },
    label: local("Bloque 3", "Block 3"),
    sessions: [
      session(
        "b5-heberht",
        "bisa",
        "Más allá del Prompt: Construyendo sistemas RAG para que tu IA deje de alucinar",
        ["Heberht Castellon"],
        "charla",
        "intermedio",
      ),
      session(
        "b3-kaya",
        "gessell",
        "Inteligencia Artificial, Machine Learning y Generative AI",
        ["Kaya Platzer"],
        "charla",
        "intermedio",
      ),
      session(
        "b3-fernando",
        "a1",
        "Ship Code on AWS: Hands-On IaC & Automation",
        ["Fernando Iquiza"],
        "charla",
        "intro",
      ),
      session(
        "b3-luis",
        "l29",
        "Angular Agéntico: Genera código moderno en Kiro IDE usando Model Context Protocol (MCP)",
        ["Luis Enrique Ledezma Lopez"],
        "demo",
        "intermedio",
      ),
      session(
        "v5",
        "virtual-es",
        "Cloud no es solo aprender servicios: Cómo empezar a tomar decisiones de ingeniería",
        ["Jesús Aguirre"],
        "charla",
        "intro",
      ),
      session(
        "v2",
        "virtual-en",
        "Architecture's Evolution: From Stonehenge Monoliths up to Smart Multi Agent Architectures",
        ["Socrates Ruiz"],
        "charla",
        "intermedio",
      ),
    ],
  },
  {
    kind: "parallel",
    id: "bloque-4",
    time: { start: "11:45", end: "12:25" },
    label: local("Bloque 4", "Block 4"),
    sessions: [
      session(
        "b4-gonzalo",
        "bisa",
        "RAG sin quebrar tus finanzas: Búsqueda vectorial a escala con Amazon S3 Vectors y Bedrock Knowledge",
        ["Gonzalo Alfaro"],
        "charla",
        "intermedio",
      ),
      session(
        "b4-catriel",
        "gessell",
        "No todo está en Python: Construyendo agentes de IA con Bedrock y AgentCore en C#",
        ["Catriel Pereira"],
        "charla",
        "intermedio",
      ),
      session(
        "b4-carlos-roca",
        "d1",
        "Como una mamushka",
        ["Carlos Roca"],
        "charla",
        "intro",
      ),
      session(
        "v6",
        "virtual-es",
        "Defensa Contra las Artes Oscuras de los data pipelines: hazlo más robusto",
        ["Carlos Chicata"],
        "charla",
        "intermedio",
      ),
      session(
        "v4",
        "virtual-en",
        "Get Paid to Learn in Public: How LFX Mentorship Took Me From Student to CNCF Contributor",
        ["Mohammed Firdous Araoye"],
        "charla",
        "intro",
      ),
    ],
  },
  {
    kind: "parallel",
    id: "career-panel",
    time: { start: "12:30", end: "13:10" },
    label: local("Panel de carrera", "Career panel"),
    wide: true,
    note: local(
      "Los streams virtuales ofrecen panel opcional y pausa hasta las 14:00.",
      "The virtual streams have an optional panel and pause until 14:00.",
    ),
    sessions: [
      {
        ...session(
          "career",
          "bisa",
          "Building Your Career Before Graduation",
          [
            "Silvana Gutierrez",
            "Gonzalo Alfaro",
            "Carlos Isaac Jaldin Benavides",
            "Victor Altamirano",
          ],
          "panel",
          "intro",
        ),
        moderator: "Gabriel Olarte (Gabo)",
      },
    ],
  },
  {
    kind: "plenary",
    id: "lunch",
    time: { start: "13:10", end: "14:00" },
    subtype: "lunch",
    title: local("Almuerzo + Community Expo", "Lunch + Community Expo"),
    summary: local(
      "Sin sesiones técnicas. El evento vuelve a converger.",
      "No technical sessions. The event comes back together.",
    ),
  },
  {
    kind: "parallel",
    id: "bloque-5",
    time: { start: "14:00", end: "14:40" },
    label: local("Bloque 5", "Block 5"),
    sessions: [
      session(
        "b5-carlos",
        "bisa",
        "De la carpeta de apuntes al 100: un agente de IA que arma tu exposición con AWS Bedrock",
        ["Carlos Isaac Jaldin Benavides"],
        "demo",
        "intermedio",
      ),
      session(
        "b3-mauricio",
        "gessell",
        "Infraestructura Cloud, Gobernanza y Arquitectura de Datos para el manejo de IA",
        ["Mauricio Illanes"],
        "charla",
        "intermedio",
      ),
      session(
        "v7",
        "virtual-es",
        "4 errores en Producción que cambiaron mi forma de trabajar con AWS",
        ["Jean Reyes"],
        "charla",
        "intermedio",
      ),
      session(
        "v8",
        "virtual-en",
        "Securing Serverless Enterprises Against Agentic AI Threats + Evolving from Risk to Resilience",
        ["Daniel Clement"],
        "charla",
        "intermedio",
      ),
    ],
  },
  {
    kind: "parallel",
    id: "bloque-6",
    time: { start: "14:45", end: "15:25" },
    label: local("Bloque 6", "Block 6"),
    sessions: [
      session(
        "sara",
        "bisa",
        "No estaba lista, pero dije que sí: de estudiante a Solution Architect en FOX",
        ["Sara Salazar Paredes"],
        "charla",
        "intro",
      ),
      session(
        "b6-adrian",
        "gessell",
        "AI-Ops deploying your agent with behavioral metrics",
        ["Adrian Acarapi"],
        "charla",
        "intermedio",
      ),
      session(
        "b6-odaliz",
        "a1",
        "Agentes que no alucinan tu infraestructura",
        ["Odaliz Rojas"],
        "charla",
        "intermedio",
      ),
      session(
        "b6-lightning",
        "d1",
        "Infrastructure + Context Lightning Block",
        ["Alvaro Flores", "Fernando Quinteros Gutierrez"],
        "charla",
        "intermedio",
      ),
      session(
        "b8-abel",
        "virtual-es",
        "Networking para IA: El protocolo que mueve datos masivos en la era de la IA",
        ["Abel Archila"],
        "charla",
        "intermedio",
      ),
    ],
  },
  {
    kind: "plenary",
    id: "break-2",
    time: { start: "15:25", end: "15:40" },
    subtype: "break",
    title: local("Community Break"),
    summary: local(
      "Pausa y preparación para la transición cultural. Los streams virtuales también entran en pausa.",
      "Break and preparation for the cultural transition. The virtual streams also pause.",
    ),
  },
  {
    kind: "parallel",
    id: "bloque-7",
    time: { start: "15:40", end: "16:20" },
    label: local("Bloque 7 + Featured Lightning", "Block 7 + Featured Lightning"),
    note: local(
      "BISA cierra desde las 16:20 para el sound check.",
      "BISA closes from 16:20 for sound check.",
    ),
    sessions: [
      session(
        "b7-pablo",
        "gessell",
        "Cuando tu servidor desaparece",
        ["Pablo Daniel Noya Quiroz"],
        "charla",
        "intermedio",
      ),
    ],
  },
  {
    kind: "parallel",
    id: "bloque-8",
    time: { start: "16:25", end: "17:05" },
    label: local("Bloque 8", "Block 8"),
    note: local(
      "BISA cerrado por sound check y Gessell libre para la transición al acto cultural.",
      "BISA closed for sound check and Gessell free for the cultural-act transition.",
    ),
    sessions: [
      session(
        "b5-jose",
        "a1",
        "¿Le darías las llaves de tu empresa a una IA? Cómo evaluar agentes y evitar errores costosos",
        ["Jose Matias Medinaceli Saavedra"],
        "charla",
        "intermedio",
      ),
    ],
  },
  {
    kind: "plenary",
    id: "cultural",
    time: { start: "17:05", end: "17:30" },
    subtype: "keynote",
    title: local("Acto cultural", "Cultural act"),
    summary: local(
      "BISA es el único espacio activo. Stream opcional.",
      "BISA is the only active space. Optional stream.",
    ),
  },
  {
    kind: "plenary",
    id: "closing",
    time: { start: "17:30", end: "17:45" },
    subtype: "closing",
    title: local("Closing Session + Community Recognition"),
    summary: local(
      "Recapitulación, agradecimientos y reconocimiento a la comunidad.",
      "Recap, thanks and recognition for the community.",
    ),
  },
  {
    kind: "plenary",
    id: "community-call",
    time: { start: "17:45", end: "18:00" },
    subtype: "networking",
    title: local("Community Call + Networking"),
    summary: local(
      "Próximos eventos, comunidades presentes, foto final y networking.",
      "Upcoming events, participating communities, final photo and networking.",
    ),
  },
] as const satisfies readonly AgendaBlock[];

export const dayRhythm = [
  { code: "01", time: "08:00", label: local("Registro + Expo", "Registration + Expo") },
  {
    code: "02",
    time: "09:20",
    label: local("Sesiones presenciales + virtuales", "In-person + virtual sessions"),
  },
  { code: "03", time: "12:30", label: local("Panel de carrera", "Career panel") },
  { code: "04", time: "13:10", label: local("Almuerzo + Expo", "Lunch + Expo") },
  {
    code: "05",
    time: "16:25",
    label: local("Transición cultural", "Cultural transition"),
  },
  {
    code: "06",
    time: "17:05",
    label: local("Acto cultural + cierre", "Cultural act + closing"),
  },
] as const;
