import type { AgendaBlock, AgendaTrack, AgendaTrackId, ScheduleTrackId } from "./types";

const local = (es: string, en = es) => ({ es, en });

/** Rooms and the independent stream in the published programme. */
export const agendaTracks = [
  {
    id: "bisa",
    kind: "room",
    name: local("Auditorio BISA", "BISA Auditorium"),
    shortName: local("BISA"),
    code: "01",
    accent: "orange",
    room: "Main Stage",
    description: local("Escenario principal", "Main stage"),
    topics: { es: [], en: [] },
    icon: "rocket",
  },
  {
    id: "gessell",
    kind: "room",
    name: local("Salón Gessell", "Gessell Hall"),
    shortName: local("Gessell"),
    code: "02",
    accent: "sky",
    room: "Secondary Stage",
    description: local("Escenario secundario", "Secondary stage"),
    topics: { es: [], en: [] },
    icon: "ai",
  },
  {
    id: "d1",
    kind: "room",
    name: local("Diseño 1", "Design 1"),
    shortName: local("D1"),
    code: "03",
    accent: "purple",
    room: "Specialized Talks",
    description: local("Charlas especializadas", "Specialized talks"),
    topics: { es: [], en: [] },
    icon: "key",
  },
  {
    id: "l22",
    kind: "room",
    name: local("Diseño 2", "Design 2"),
    shortName: local("D2"),
    code: "04",
    accent: "green",
    room: "PC Lab",
    description: local("Laboratorio con PCs", "Computer lab"),
    topics: { es: [], en: [] },
    icon: "dumbbell",
  },
  {
    id: "a1",
    kind: "virtual",
    name: local("Arquitectura 1 · Híbrido español", "Architecture 1 · Hybrid Spanish"),
    shortName: local("A1 · Híbrido ES", "A1 · Hybrid ES"),
    code: "05",
    accent: "green",
    room: "Hybrid Talks",
    description: local("Charlas híbridas en español", "Hybrid talks in Spanish"),
    topics: { es: [], en: [] },
    icon: "bolt",
  },
  {
    id: "a2",
    kind: "virtual",
    name: local("Arquitectura 2 · Híbrido inglés", "Architecture 2 · Hybrid English"),
    shortName: local("A2 · Híbrido EN", "A2 · Hybrid EN"),
    code: "06",
    accent: "sky",
    room: "Hybrid Talks",
    description: local("Charlas híbridas en inglés", "Hybrid talks in English"),
    topics: { es: [], en: [] },
    icon: "ai",
  },
] as const satisfies readonly AgendaTrack[];

export function getAgendaTrack(id: ScheduleTrackId): AgendaTrack {
  const track = agendaTracks.find((item) => item.id === id);
  if (!track) throw new Error(`Sala desconocida: ${id}`);
  return track;
}

const session = (
  id: string,
  trackId: AgendaTrackId,
  title: string,
  speakers: readonly string[],
  format: "charla" | "taller" | "demo" | "panel" | "caso" | "lightning" = "charla",
  level?: "intro" | "intermedio" | "avanzado",
  time?: {
    start: `${number}${number}:${number}${number}`;
    end: `${number}${number}:${number}${number}`;
  },
) => ({
  kind: "session" as const,
  id,
  trackId,
  status: "confirmed" as const,
  title,
  speakers,
  format,
  level,
  time,
});

/** Published programme, including the Spanish and English virtual streams. */
export const agenda = [
  {
    kind: "plenary",
    id: "registro",
    time: { start: "08:00", end: "09:00" },
    subtype: "registration",
    title: local("Registro + Community Expo", "Registration + Community Expo"),
    summary: local(
      "Acreditación, stands, networking inicial y visuales del evento.",
      "Check-in, booths, early networking and event visuals.",
    ),
  },
  {
    kind: "plenary",
    id: "opening",
    time: { start: "09:00", end: "09:15" },
    subtype: "opening",
    title: local(
      "Apertura — Opening AWS Student Community Day Cochabamba 2026",
      "Opening — AWS Student Community Day Cochabamba 2026",
    ),
    summary: local(
      "Bienvenida, comunidades, sponsors, tracks y espacios.",
      "Welcome, communities, sponsors, tracks and spaces.",
    ),
  },
  {
    kind: "plenary",
    id: "breakfast",
    time: { start: "09:15", end: "09:30" },
    subtype: "break",
    title: local("Desayuno", "Breakfast"),
  },
  {
    kind: "parallel",
    id: "hibrido-1",
    time: { start: "10:20", end: "11:00" },
    label: local("Sesiones híbridas", "Hybrid sessions"),
    sessions: [
      session(
        "v3",
        "a1",
        "Construye tu Primer MCP Server de Seguridad en AWS",
        ["Jorge Barreto"],
        "charla",
        "intermedio",
        { start: "10:20", end: "11:00" },
      ),
      session(
        "v1",
        "a2",
        "From Complex Orchestration to Declarative Data Pipelines with AWS Glue",
        ["Vikneshwara R B"],
        "charla",
        "intermedio",
        { start: "10:20", end: "11:00" },
      ),
    ],
  },
  {
    kind: "parallel",
    id: "bloque-1",
    time: { start: "11:00", end: "11:40" },
    label: local("Bloque 1", "Block 1"),
    sessions: [
      session(
        "b1-victor",
        "bisa",
        "Monitorea como un Pro: CloudWatch + APIs .NET en tiempo real",
        ["Victor Altamirano"],
        "charla",
        "intermedio",
      ),
      session(
        "b1-carlos",
        "gessell",
        "Building Autonomous AI on AWS: From Bedrock to Real-World Agent Systems",
        ["Carlos Olivera"],
        "charla",
        "intermedio",
      ),
      session(
        "b7-pablo",
        "d1",
        "Cuando tu servidor desaparece",
        ["Pablo Daniel Noya Quiroz"],
        "charla",
        "intermedio",
      ),
      session(
        "b1-marlene",
        "l22",
        "Construye tu primera app de IA con AWS + PartyRock",
        ["Marlene Choque Perez", "Araceli Ivana Challapa Montaño"],
        "taller",
        "intro",
      ),
      session(
        "v5",
        "a1",
        "Cloud no es solo aprender servicios: Cómo empezar a tomar decisiones de ingeniería",
        ["Jesús Aguirre"],
        "charla",
        "intro",
        { start: "11:05", end: "11:45" },
      ),
      session(
        "v2",
        "a2",
        "Architecture's Evolution: From Stonehenge Monoliths up to Smart Multi Agent Architectures",
        ["Socrates Ruiz"],
        "charla",
        "intermedio",
        { start: "11:10", end: "11:50" },
      ),
    ],
  },
  {
    kind: "parallel",
    id: "bloque-2",
    time: { start: "12:30", end: "13:10" },
    label: local("Bloque 2", "Block 2"),
    sessions: [
      session(
        "b2-silvana",
        "bisa",
        "Sin datos no hay IA: construyendo un pipeline ETL serverless en AWS",
        ["Silvana Gutierrez", "Micaela Belen Challapa Montaño"],
        "charla",
        "intermedio",
      ),
      session(
        "b2-freddy",
        "gessell",
        "De la idea al código: construyamos una aplicación con AI-DLC",
        ["Freddy Aguilar Rojas", "Natalia Alfaro"],
        "taller",
        "intro",
      ),
      session(
        "b2-juan",
        "d1",
        "El mindset DevOps que nadie te enseña en la universidad",
        ["Juan Rodrigo Villarroel Calderon"],
        "charla",
        "intro",
      ),
      session(
        "b2-rodrigo",
        "l22",
        "De programar con IA a construir con agentes",
        ["Rodrigo Torrico"],
        "charla",
        "intermedio",
      ),
      session(
        "v6",
        "a1",
        "Defensa Contra las Artes Oscuras de los data pipelines: hazlo más robusto",
        ["Carlos Chicata"],
        "charla",
        "intermedio",
        { start: "12:30", end: "13:10" },
      ),
      session(
        "v4",
        "a2",
        "Get Paid to Learn in Public: How LFX Mentorship Took Me From Student to CNCF Contributor",
        ["Mohammed Firdous Araoye"],
        "charla",
        "intro",
        { start: "12:40", end: "13:20" },
      ),
    ],
  },
  {
    kind: "plenary",
    id: "food-trucks",
    time: { start: "13:10", end: "13:30" },
    subtype: "break",
    title: local("Food trucks + Community Expo", "Food trucks + Community Expo"),
    summary: local(
      "Pausa de comida y expo. Las sesiones presenciales vuelven a las 13:30.",
      "Food and expo break. In-person sessions resume at 13:30.",
    ),
  },
  {
    kind: "parallel",
    id: "bloque-3",
    time: { start: "13:30", end: "14:10" },
    label: local("Bloque 3", "Block 3"),
    note: local(
      "Auditorio BISA: Heberht comienza a las 14:30.",
      "BISA Auditorium: Heberht starts at 14:30.",
    ),
    sessions: [
      session(
        "b5-heberht",
        "bisa",
        "Más allá del Prompt: Construyendo sistemas RAG para que tu IA deje de alucinar",
        ["Heberht Castellon"],
        "charla",
        "intermedio",
        { start: "14:30", end: "15:10" },
      ),
      session(
        "b3-kaya",
        "gessell",
        "Inteligencia Artificial, Machine Learning y Generative AI",
        ["Kaya Platzer"],
        "charla",
        "intermedio",
      ),
      session(
        "b3-fernando",
        "d1",
        "Ship Code on AWS: Hands-On IaC & Automation",
        ["Fernando Iquiza"],
        "charla",
        "intro",
      ),
      session(
        "b3-luis",
        "l22",
        "Angular Agéntico: Genera código moderno en Kiro IDE usando MCP",
        ["Luis Enrique Ledezma Lopez"],
        "demo",
        "intermedio",
      ),
      session(
        "v7",
        "a1",
        "4 errores en Producción que cambiaron mi forma de trabajar con AWS",
        ["Jean Reyes"],
        "charla",
        "intermedio",
        { start: "13:15", end: "13:55" },
      ),
      session(
        "v8",
        "a2",
        "Securing Serverless Enterprises Against Agentic AI Threats",
        ["Daniel Clement"],
        "charla",
        "intermedio",
        { start: "13:30", end: "13:50" },
      ),
    ],
  },
  {
    kind: "parallel",
    id: "hibrido-2",
    time: { start: "14:00", end: "14:40" },
    label: local("Sesión híbrida", "Hybrid session"),
    sessions: [
      session(
        "b8-abel",
        "a1",
        "Networking para IA: El protocolo que mueve datos masivos en la era de la IA",
        ["Abel Archila"],
        "charla",
        "intermedio",
        { start: "14:00", end: "14:40" },
      ),
    ],
  },
  {
    kind: "parallel",
    id: "bloque-4",
    time: { start: "14:20", end: "15:00" },
    label: local("Bloque 4", "Block 4"),
    sessions: [
      session(
        "b4-gonzalo",
        "bisa",
        "RAG sin quebrar tus finanzas: Búsqueda vectorial a escala con Amazon S3 Vectors y Bedrock Knowledge",
        ["Gonzalo Alfaro"],
        "charla",
        "intermedio",
        { start: "15:20", end: "16:00" },
      ),
      session(
        "b4-catriel",
        "gessell",
        "No todo está en Python: Construyendo agentes de IA con Bedrock y AgentCore en C#",
        ["Catriel Pereira"],
        "charla",
        "intermedio",
      ),
      session(
        "b5-jose",
        "d1",
        "¿Le darías las llaves de tu empresa a una IA? Cómo evaluar agentes y evitar errores costosos",
        ["Jose Matias Medinaceli Saavedra"],
        "charla",
        "intermedio",
      ),
      session(
        "b7-juan-manuel",
        "a1",
        "Más allá del código: cómo una comunidad puede cambiar tu carrera",
        ["Juan Manuel Hoyos"],
        "lightning",
        "intro",
        { start: "14:45", end: "15:05" },
      ),
    ],
  },
  {
    kind: "parallel",
    id: "bloque-5",
    time: { start: "15:10", end: "15:50" },
    label: local("Bloque 5", "Block 5"),
    sessions: [
      session(
        "b5-carlos",
        "bisa",
        "De la carpeta de apuntes al 100: un agente de IA que arma tu exposición con AWS Bedrock",
        ["Carlos Isaac Jaldin Benavides"],
        "demo",
        "intermedio",
        { start: "16:10", end: "16:50" },
      ),
      session(
        "b3-mauricio",
        "gessell",
        "Infraestructura Cloud, Gobernanza y Arquitectura de Datos para el manejo de IA",
        ["Mauricio Illanes"],
        "charla",
        "intermedio",
      ),
      session(
        "b6-lightning",
        "d1",
        "Infrastructure + Context Lightning Block",
        ["Alvaro Flores", "Fernando Quinteros Gutierrez"],
        "charla",
        "intermedio",
      ),
    ],
  },
  {
    kind: "parallel",
    id: "bloque-6",
    time: { start: "16:00", end: "16:40" },
    label: local("Bloque 6", "Block 6"),
    sessions: [
      session(
        "sara",
        "bisa",
        "No estaba lista, pero dije que sí: de estudiante a Solution Architect en FOX",
        ["Sara Salazar Paredes"],
        "charla",
        "intro",
        { start: "17:00", end: "17:40" },
      ),
      session(
        "b6-adrian",
        "gessell",
        "AI-Ops deploying your agent with behavioral metrics",
        ["Adrian Acarapi"],
        "charla",
        "intermedio",
      ),
      session(
        "b6-odaliz",
        "d1",
        "Agentes que no alucinan tu infraestructura",
        ["Odaliz Rojas"],
        "charla",
        "intermedio",
      ),
    ],
  },
  {
    kind: "plenary",
    id: "break-2",
    time: { start: "16:40", end: "16:50" },
    subtype: "break",
    title: local("Community Break"),
    summary: local(
      "Pausa en las demás salas. BISA continúa hasta las 16:50.",
      "Break in the other rooms. BISA continues until 16:50.",
    ),
  },
  {
    kind: "parallel",
    id: "bloque-7",
    time: { start: "16:50", end: "17:30" },
    label: local("Bloque 7", "Block 7"),
    note: local(
      "Auditorio BISA: charla de Sara hasta las 17:40; luego sound check.",
      "BISA Auditorium: Sara's talk until 17:40, then sound check.",
    ),
    sessions: [
      session(
        "b7-rene",
        "gessell",
        "La nube no es segura por defecto: errores de IAM que vemos una y otra vez",
        ["Rene Sosa"],
        "charla",
        "intermedio",
      ),
      session(
        "b4-carlos-roca",
        "d1",
        "Como una mamushka",
        ["Carlos Roca"],
        "charla",
        "intro",
      ),
    ],
  },
  {
    kind: "plenary",
    id: "cultural",
    time: { start: "18:20", end: "18:40" },
    subtype: "keynote",
    title: local("Keynote & Acto Cultural", "Keynote & Cultural Act"),
    summary: local(
      "Auditorio BISA, único espacio presencial activo. Stream opcional.",
      "BISA Auditorium, the only active in-person space. Optional stream.",
    ),
  },
  {
    kind: "plenary",
    id: "closing",
    time: { start: "18:40", end: "18:55" },
    subtype: "closing",
    title: local(
      "Cierre — Closing Session + Community Recognition",
      "Closing Session + Community Recognition",
    ),
    summary: local(
      "Recapitulación, agradecimientos y reconocimiento a la comunidad.",
      "Recap, thanks and recognition for the community.",
    ),
  },
  {
    kind: "plenary",
    id: "community-call",
    time: { start: "18:55", end: "19:10" },
    subtype: "networking",
    title: local(
      "Networking — Community Call + Networking",
      "Community Call + Networking",
    ),
    summary: local(
      "Próximos eventos, comunidades presentes, foto final y networking general.",
      "Upcoming events, participating communities, final photo and open networking.",
    ),
  },
] as const satisfies readonly AgendaBlock[];

export const dayRhythm = [
  { code: "01", time: "08:00", label: local("Registro + Expo", "Registration + Expo") },
  { code: "02", time: "10:20", label: local("Sesiones híbridas", "Hybrid sessions") },
  {
    code: "03",
    time: "11:00",
    label: local("Sesiones presenciales + híbridas", "In-person + hybrid sessions"),
  },
  { code: "04", time: "13:10", label: local("Food trucks + Expo", "Food trucks + Expo") },
  {
    code: "05",
    time: "16:40",
    label: local("Transición cultural", "Cultural transition"),
  },
  {
    code: "06",
    time: "18:20",
    label: local("Keynote, acto cultural + cierre", "Keynote, cultural act + closing"),
  },
] as const;
